# This is a basic workflow to help you get started with Actions

name: 3D Contributions

on:
  schedule: 
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.4.0
        env:
          USERNAME: ${{ mehmetalicakir }}
      - name: Commit & Push
        run: |
          git config user.name Mehmet Ali ÇAKIR
          git config user.email cakiroglu_m.ali@hotmail.com
          git add -A .
          git commit -m "generated"
          git pusher that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
